vlog -work work C:/Study/Computerarchitecture/Milestone2/00_src/singlecycle/simulation/modelsim/Waveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.singlecycle_vlg_vec_tst
onerror {resume}
add wave {singlecycle_vlg_vec_tst/i1/i_io_btn}
add wave {singlecycle_vlg_vec_tst/i1/i_io_btn[3]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_btn[2]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_btn[1]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_btn[0]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[31]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[30]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[29]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[28]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[27]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[26]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[25]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[24]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[23]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[22]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[21]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[20]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[19]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[18]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[17]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[16]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[15]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[14]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[13]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[12]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[11]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[10]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[9]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[8]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[7]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[6]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[5]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[4]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[3]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[2]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[1]}
add wave {singlecycle_vlg_vec_tst/i1/i_io_sw[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[31]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[30]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[29]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[28]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[27]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[26]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[25]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[24]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[23]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[22]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[21]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[20]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[19]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[18]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[17]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[16]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[15]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[14]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[13]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[12]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[11]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[10]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[9]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[8]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[7]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_pc_debug[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[31]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[30]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[29]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[28]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[27]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[26]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[25]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[24]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[23]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[22]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[21]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[20]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[19]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[18]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[17]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[16]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[15]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[14]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[13]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[12]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[11]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[10]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[9]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[8]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[7]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_lcd[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[31]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[30]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[29]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[28]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[27]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[26]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[25]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[24]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[23]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[22]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[21]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[20]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[19]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[18]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[17]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[16]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[15]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[14]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[13]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[12]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[11]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[10]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[9]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[8]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[7]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledg[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[31]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[30]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[29]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[28]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[27]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[26]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[25]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[24]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[23]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[22]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[21]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[20]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[19]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[18]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[17]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[16]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[15]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[14]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[13]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[12]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[11]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[10]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[9]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[8]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[7]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_ledr[0]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[17]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[16]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[15]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[14]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[13]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[12]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[11]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[10]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[9]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[8]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[7]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[6]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[5]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[4]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[3]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[2]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[1]}
add wave {singlecycle_vlg_vec_tst/i1/addr_to_sram[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex0[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex1[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex2[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex3[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex4[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex5[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex6[0]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[6]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[5]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[4]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[3]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[2]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[1]}
add wave {singlecycle_vlg_vec_tst/i1/o_io_hex7[0]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[15]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[14]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[13]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[12]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[11]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[10]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[9]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[8]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[7]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[6]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[5]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[4]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[3]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[2]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[1]}
add wave {singlecycle_vlg_vec_tst/i1/sramdq[0]}
add wave {singlecycle_vlg_vec_tst/i1/i_clk}
add wave {singlecycle_vlg_vec_tst/i1/i_rst_n}
add wave {singlecycle_vlg_vec_tst/i1/o_insn_vld}
add wave {singlecycle_vlg_vec_tst/i1/sramcen}
add wave {singlecycle_vlg_vec_tst/i1/sramlbn}
add wave {singlecycle_vlg_vec_tst/i1/sramoen}
add wave {singlecycle_vlg_vec_tst/i1/sramubn}
add wave {singlecycle_vlg_vec_tst/i1/sramwen}
run -all
